site_name: FPS
site_description: Fast Pluggable System
repo_url: https://github.com/jupyter-server/fps

theme:
  name: 'material'
  palette:
    - scheme: default
      primary: 'black'
      accent: 'black'
      toggle:
          icon: material/lightbulb-outline
          name: Switch to dark mode
    - scheme: slate
      primary: 'black'
      accent: 'black'
      toggle:
          icon: material/lightbulb
          name: Switch to light mode
  features:
    - navigation.instant
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
  logo: jupyter.svg

nav:
- Overview: index.md
- install.md
- guide.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_source: false
          docstring_style: google
          find_stubs_package: true
          docstring_options:
            ignore_init_summary: false
